import json
import re

with open('admin/app.js', 'r', encoding='utf-8') as f:
    content = f.read()

arabic_dict = {
    'Dashboard': 'لوحة القيادة', 'Total Revenue': 'إجمالي الإيرادات', 'Active Drivers': 'السائقين النشطين',
    'Pending Requests': 'الطلبات المعلقة', 'Completed Collections': 'المجموعات المكتملة', 'Quick Actions': 'إجراءات سريعة',
    'Generate Reports': 'إنشاء تقارير', 'System Settings': 'إعدادات النظام', 'Save All Settings': 'حفظ جميع الإعدادات',
    'Logout': 'تسجيل خروج', 'Global System Preferences': 'تفضيلات النظام العالمية',
    'Smart Waste Admin': 'إدارة النفايات الذكية',
    'Messages': 'الرسائل',
    '0 New': '0 جديد',
    'View All Messages': 'عرض جميع الرسائل',
    'Notifications': 'الإشعارات',
    'Mark all as read': 'تحديد الكل كمقروء',
    'My Profile': 'ملفي الشخصي',
    'Settings': 'الإعدادات',
    'View All Requests': 'عرض جميع الطلبات',
    'Manage Residents': 'إدارة السكان',
    'Assign Driver': 'تعيين سائق',
    'Manage Drivers': 'إدارة السائقين',
    'Payments': 'المدفوعات',
    'Messages & Reports': 'الرسائل والتقارير',
    'Monitor System & Reports': 'مراقبة النظام',
    'Profile': 'الملف الشخصي',
    'Total Waste Requests': 'إجمالي طلبات النفايات',
    'Completed Requests': 'الطلبات المكتملة',
    'Total Residents': 'إجمالي السكان',
    'Total Payments': 'إجمالي المدفوعات',
    'Monthly Revenue': 'الإيرادات الشهرية',
    "Today's Collections": 'مجموعات اليوم',
    'Monthly Requests': 'الطلبات الشهرية',
    'Request Status': 'حالة الطلب',
    'Driver Performance': 'أداء السائق',
    'Jobs Completed': 'الوظائف المكتملة',
    'Assigned/In-Progress': 'معين/قيد التقدم',
    'Requests Made': 'الطلبات المقدمة',
    'Resident': 'مقيم',
    'Area': 'المنطقة',
    'Waste Type': 'نوع النفايات',
    'Driver': 'السائق',
    'Vehicle': 'المركبة',
    'Vehicle Info': 'معلومات المركبة',
    'Vehicle Info (License Plate/Type)': 'معلومات المركبة (لوحة الترخيص/النوع)',
    'Status': 'الحالة',
    'Action': 'إجراء',
    'Pending': 'قيد الانتظار',
    'Completed': 'مكتمل',
    'Assign': 'تعيين',
    'Details': 'تفاصيل',
    'Add New Driver': 'إضافة سائق جديد',
    'Manage Payments': 'إدارة المدفوعات',
    'Live System Activity Logs': 'سجلات نشاط النظام',
    'Notification Settings': 'إعدادات الإشعارات',
    'Report Generation': 'إنشاء التقارير',
    'Report Type': 'نوع التقرير',
    'Date Range': 'نطاق التاريخ',
    'Preview': 'معاينة',
    'Print': 'طباعة',
    'Download PDF': 'تحميل PDF',
    'Export Excel': 'تصدير Excel',
    'Save All Settings': 'حفظ الإعدادات',
    'Clear': 'مسح',
    'Waste Collection Overview': 'نظرة عامة على جمع النفايات',
    'Search residents, drivers...': 'البحث عن سكان، سائقين...',
    'Search drivers, areas, reports...': 'البحث في السائقين والمناطق والتقارير...',
    'Admin Authenticated': 'تمت مصادقة المسؤول',
    'CRON Job Executed': 'تم تنفيذ مهمة CRON',
    'Driver App Sync': 'مزامنة تطبيق السائق',
    'Database Latency': 'زمن انتقال قاعدة البيانات',
    'Payment Processed': 'تمت معالجة الدفع',
    'Dark Mode': 'الوضع المظلم',
    'System Timezone': 'المنطقة الزمنية',
    'Currency Display': 'عرض العملة',
    'Dashboard Language': 'لغة لوحة القيادة',
    'Email Notifications for New Requests': 'إشعارات البريد لطلبات جديدة',
    'SMS Alerts for Failed Payments': 'تنبيهات SMS للمدفوعات الفاشلة',
    'Receive Weekly System Summary': 'تلقي ملخص النظام الأسبوعي',
    'Enable dark theme for the dashboard': 'تمكين المظهر الداكن للوحة القيادة',
    'Get an email every time a resident makes a new waste collection request.': 'احصل على بريد عند قيام مقيم بطلب جمع نفايات جديد.',
    'Immediate SMS alert to Admin if a payment transaction fails.': 'تنبيه SMS فوري للإدارة إذا فشلت معاملة الدفع.',
    'Automated PDF report sent to your email every Sunday.': 'تقرير PDF آلي يُرسل إلى بريدك كل يوم أحد.',
    'Recent Support Messages': 'رسائل الدعم الحديثة',
    'View All': 'عرض الكل',
    'All logs cleared.': 'تم مسح جميع السجلات.',
    'Active Accounts': 'الحسابات النشطة',
    'Inactive Accounts': 'الحسابات غير النشطة',
    'Search by name, email, or phone..': 'البحث بالاسم أو البريد أو الهاتف..',
    'All Addresses': 'جميع العناوين',
    'Resident ID': 'معرف المقيم',
    'Name': 'الاسم',
    'Email': 'البريد الإلكتروني',
    'Phone Number': 'رقم الهاتف',
    'Address': 'العنوان',
    'Actions': 'إجراءات',
    'View': 'عرض',
    'Delete': 'حذف',
    'Showing 1 to 3 of 3 entries': 'إظهار 1 إلى 3 من 3 إدخالات',
    'Previous': 'السابق',
    'Next': 'التالي',
    'Search name or phone...': 'البحث بالاسم أو الهاتف...',
    'All Zones': 'جميع المناطق',
    'Driver ID': 'معرف السائق',
    'Vehicle Info': 'معلومات المركبة',
    'Zone / Area': 'المنطقة / الحي',
    'Total Drivers': 'إجمالي السائقين',
    'Active (Online)': 'نشط (متصل)',
    'Offline': 'غير متصل',
    'Payments & Revenue': 'المدفوعات والإيرادات',
    'Last 6 Months': 'آخر 6 أشهر',
    'This Month': 'هذا الشهر',
    'Last 7 Days': 'آخر 7 أيام',
    'Generate Financial Report': 'إنشاء تقرير مالي',
    'Total Transactions': 'إجمالي المعاملات',
    'Pending Payments': 'المدفوعات المعلقة',
    'Failed Payments': 'المدفوعات الفاشلة',
    'Revenue Over Time (6 Months)': 'الإيرادات بمرور الوقت (6 أشهر)',
    'Payment Status Breakdown': 'توزيع حالة الدفع',
    'Recent Transactions': 'المعاملات الأخيرة',
    'Transaction ID': 'معرف المعاملة',
    'Amount': 'المبلغ',
    'Method': 'الطريقة',
    'All Messages': 'جميع الرسائل',
    'Only Residents': 'المقيمين فقط',
    'Only Drivers': 'السائقين فقط',
    'Mark All as Read': 'تحديد الكل كمقروء',
    'Date/Time': 'التاريخ/الوقت',
    'Sender': 'المرسل',
    'Role': 'الدور',
    'Message': 'الرسالة',
    'System Monitoring & Reports': 'مراقبة النظام والتقارير',
    'Loading residents...': 'جاري تحميل السكان...',
    'Loading drivers...': 'جاري تحميل السائقين...',
    'Loading...': 'جاري التحميل...',
    'Recent Requests': 'الطلبات الحديثة',
    'Search...': 'بحث...',
    'All Status': 'جميع الحالات',
    'ID': 'المعرف',
    'Type': 'النوع',
    'Driver': 'السائق',
    'Req Date': 'تاريخ الطلب',
    'Assigned': 'تم التعيين',
    'Done': 'اكتمل',
    'Unassigned': 'غير معين',
    'Driver Status Panel': 'لوحة حالة السائق',
    'DRIVER': 'السائق',
    'VEHICLE': 'المركبة',
    'Online': 'متصل',
    'General': 'عام',
    'Recycling': 'إعادة تدوير',
    'Hazardous': 'خطرة',
    'Bulk': 'ضخمة',
    'Recent Activities Timeline': 'الجدول الزمني للأنشطة الأخيرة',
    "Today's Collection Schedule": 'جدول المجموعات اليوم',
    'Time': 'الوقت',
    'Priority': 'الأولوية',
    'Low': 'منخفضة',
    'Med': 'متوسطة',
    'High': 'عالية',
    'Request Created': 'تم إنشاء الطلب',
    'Payment Received': 'تم استلام الدفع',
    'Driver Assigned': 'تم تعيين السائق',
    'No scheduled collections': 'لا توجد مجموعات مجدولة',
    'No recent activities': 'لا توجد أنشطة حديثة',
    'All Waste Requests': 'جميع طلبات النفايات',
    'Search by resident or ID...': 'البحث عن طريق المقيم أو المعرف...',
    'All Statuses': 'جميع الحالات',
    'Export CSV': 'تصدير CSV',
    'Request ID': 'معرف الطلب',
    'Resident Address': 'عنوان المقيم',
    'Request Date & Time': 'تاريخ ووقت الطلب',
    'Assigned Driver': 'السائق المعين',
    'Edit': 'تعديل',
    'En Route': 'في الطريق',
    'Assign Drivers (Pending)': 'تعيين السائقين (قيد الانتظار)',
    'Resident Name': 'اسم المقيم',
    'Request Time': 'وقت الطلب',
    'Normal': 'عادي',
    'Select a driver...': 'اختر سائقًا...',
    'Smart Waste Collection Management System © 2026 | Version 1.1': 'نظام إدارة جمع النفايات الذكي © 2026 | الإصدار 1.1',
    'Enterprise Edition': 'إصدار المؤسسات',
    'System Health Status': 'حالة صحة النظام',
    'Database Server': 'خادم قاعدة البيانات',
    'Online & Healthy': 'متصل وصحي',
    'API Gateway': 'بوابة واجهة برمجة التطبيقات',
    '99.9% Uptime': 'وقت تشغيل 99.9%',
    'Generate Custom Reports': 'إنشاء تقارير مخصصة',
    'Waste Collection Summary': 'ملخص جمع النفايات',
    'Financial Revenue Report': 'تقرير الإيرادات المالية',
    'Driver Performance Report': 'تقرير أداء السائق',
    'Admin Profile': 'الملف الشخصي للمسؤول',
    'Personal Information': 'المعلومات الشخصية',
    'Upload Photo': 'رفع صورة',
    'Allowed formats: JPG, PNG. Max size: 2MB.': 'التنسيقات المسموح بها: JPG، PNG. الحد الأقصى: 2 ميجابايت.',
    'Full Name': 'الاسم الكامل',
    'Email Address': 'عنوان البريد الإلكتروني',
    'Contact IT support to change your email.': 'اتصل بدعم تكنولوجيا المعلومات لتغيير بريدك.',
    'Role / Position': 'الدور / المنصب',
    'Super Administrator': 'مدير متميز',
    'Security & Password': 'الأمان وكلمة المرور',
    'It is highly recommended to change your password every 90 days.': 'يوصى بشدة بتغيير كلمة المرور الخاصة بك كل 90 يومًا.',
    'Current Password': 'كلمة المرور الحالية',
    'Enter current password': 'أدخل كلمة المرور الحالية',
    'New Password': 'كلمة المرور الجديدة',
    'Create new password': 'إنشاء كلمة مرور جديدة',
    'Confirm New Password': 'تأكيد كلمة المرور الجديدة',
    'Confirm new password': 'تأكيد كلمة المرور الجديدة',
    'Update Password': 'تحديث كلمة المرور',
    'Save Profile': 'حفظ الملف الشخصي',
    'New passwords do not match': 'كلمات المرور الجديدة غير متطابقة',
    'Password updated successfully': 'تم تحديث كلمة المرور بنجاح',
    'Profile updated successfully': 'تم تحديث الملف الشخصي بنجاح'
}

arabic_dict_str = json.dumps(arabic_dict, ensure_ascii=False, indent=12)
arabic_dict_str = "dict = " + arabic_dict_str + ";"

# we need to replace the old arabic block
pattern = re.compile(r'if \(lang === \'Arabic\'\) \{\s*dict = \{.*?\};\s*document\.documentElement\.dir = \'rtl\';\s*\} else \{', re.DOTALL)
new_block = f"if (lang === 'Arabic') {{\n        {arabic_dict_str}\n        document.documentElement.dir = 'rtl';\n    }} else {{"

new_content = pattern.sub(new_block, content)

with open('admin/app.js', 'w', encoding='utf-8') as f:
    f.write(new_content)

print("Updated app.js with full Arabic dictionary")
